// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    GameReport: typeof import('./src/components/GameReport.vue')['default']
    Leaderboard: typeof import('./src/components/Leaderboard.vue')['default']
    'Leaderboard copy': typeof import('./src/components/Leaderboard copy.vue')['default']
    LeaderboardUser: typeof import('./src/components/LeaderboardUser.vue')['default']
  }
}

export { }
